name: TypeScript  

on:
  workflow_dispatch:  
  push:
    branches: [ master ]
    paths: 
      - './easydata.js/*' 
  pull_request:
    branches: [ master ]
    paths: 
      - './easydata.js/*' 

jobs:
  build_ant_test:

    runs-on: windows-latest

    defaults: 
      run:
        working-directory: ./easydata.js  
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm run installall

    - name: Build
      run: npm run build:prod

    - name: Test
      run: npm test

    - name: Pack
      run: npm run packall

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
        with:
          name: packs
          path: ./packs/**/*.tgz
