name: TypeScript  

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    defaults: 
      run:
        working-directory: ./easydata.js  
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm run installall
    - run: npm run build:prod
    - run: npm test
